version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: ziad
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./fund_transfer
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./fund_transfer:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: task
      DB_USER: ziad
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 5432

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  postgres_data:
